CREATE TABLE CAUTHU (
  MACT NUMERIC GENERATED AS IDENTITY PRIMARY KEY,
  HOTEN NVARCHAR2(100) NOT NULL,
  VITRI NVARCHAR2(20) NOT NULL,
  NGAYSINH DATE,
  DIACHI NVARCHAR2(200),
  MACLB VARCHAR2(5) NOT NULL,
  MAQG VARCHAR2(5) NOT NULL,
  SO INT NOT NULL
);

CREATE TABLE QUOCGIA (
  MAQG VARCHAR2(5) PRIMARY KEY,
  TENQG NVARCHAR2(60) NOT NULL
);

CREATE TABLE CAULACBO (
  MACLB VARCHAR2(5) PRIMARY KEY,
  TENCLB NVARCHAR2(100) NOT NULL,
  MASAN VARCHAR2(5) NOT NULL,
  MATINH VARCHAR2(5) NOT NULL
);

CREATE TABLE TINH (
  MATINH VARCHAR2(5) PRIMARY KEY,
  TENTINH NVARCHAR2(100) NOT NULL
);

CREATE TABLE SANVD (
  MASAN VARCHAR2(5) PRIMARY KEY,
  TENSAN NVARCHAR2(100) NOT NULL,
  DIACHI NVARCHAR2(200)
);

CREATE TABLE HUANLUYENVIEN (
  MAHLV VARCHAR2(5) PRIMARY KEY,
  TENHLV NVARCHAR2(100) NOT NULL,
  NGAYSINH DATE,
  DIACHI NVARCHAR2(200),
  DIENTHOAI NVARCHAR2(20),
  MAQG VARCHAR2(5) NOT NULL
);

CREATE TABLE HLV_CLB (
  MAHLV VARCHAR2(5),
  MACLB VARCHAR2(5),
  VAITRO NVARCHAR2(100) NOT NULL,
  PRIMARY KEY (MAHLV, MACLB)
);

CREATE TABLE TRANDAU (
  MATRAN NUMERIC GENERATED AS IDENTITY PRIMARY KEY,
  NAM INT NOT NULL,
  VONG INT NOT NULL,
  NGAYTD DATE NOT NULL,
  MACLB1 VARCHAR2(5) NOT NULL,
  MACLB2 VARCHAR2(5) NOT NULL,
  MASAN VARCHAR2(5) NOT NULL,
  KETQUA VARCHAR2(5) NOT NULL
);

CREATE TABLE BANGXH (
  MACLB VARCHAR2(5),
  NAM INT,
  VONG INT,
  SOTRAN INT NOT NULL,
  THANG INT NOT NULL,
  HOA INT NOT NULL,
  THUA INT NOT NULL,
  HIEUSO VARCHAR2(5) NOT NULL,
  DIEM INT NOT NULL,
  HANG INT NOT NULL
);

